spring:
  binlog4j:
    enabled: true
    redis-config:
      host: 123.207.217.129
      port: 6379
      password: taoren@123
    client-configs:
      master:
        inaugural: false
        mode: cluster
        persistence: true
        username: root
        password: taoren@123
        host: 123.207.217.129
        port: 3306
        serverId: 1990